name: Lint & Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          # fetch full history so we can commit/push
          fetch-depth: 0

      - name: Install Python Dependencies
        run: uv sync

      - name: Cache pre-commit hooks
        uses: actions/cache@v6.1.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.tool-versions', '.pre-commit-config.yaml') }}

      - name: Run pre-commit
        uses: tankdonut/github-actions/actions/pre-commit@v1
